package LEAD.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_AttributeDefinition;
  private ConceptPresentation props_AttributeList;
  private ConceptPresentation props_Check;
  private ConceptPresentation props_Enrich;
  private ConceptPresentation props_Query;
  private ConceptPresentation props_Select;
  private ConceptPresentation props_StreamDefinition;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.AttributeDefinition:
        if (props_AttributeDefinition == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_AttributeDefinition = cpb.create();
        }
        return props_AttributeDefinition;
      case LanguageConceptSwitch.AttributeList:
        if (props_AttributeList == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("AttributeList");
          props_AttributeList = cpb.create();
        }
        return props_AttributeList;
      case LanguageConceptSwitch.Check:
        if (props_Check == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Check");
          props_Check = cpb.create();
        }
        return props_Check;
      case LanguageConceptSwitch.Enrich:
        if (props_Enrich == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Enrich");
          props_Enrich = cpb.create();
        }
        return props_Enrich;
      case LanguageConceptSwitch.Query:
        if (props_Query == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Query");
          props_Query = cpb.create();
        }
        return props_Query;
      case LanguageConceptSwitch.Select:
        if (props_Select == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Select");
          props_Select = cpb.create();
        }
        return props_Select;
      case LanguageConceptSwitch.StreamDefinition:
        if (props_StreamDefinition == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_StreamDefinition = cpb.create();
        }
        return props_StreamDefinition;
    }
    return null;
  }
}
