package LEAD.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AttributeDefinition = 0;
  public static final int AttributeList = 1;
  public static final int Check = 2;
  public static final int Enrich = 3;
  public static final int Query = 4;
  public static final int Select = 5;
  public static final int StreamDefinition = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xebf7f592fe9245eeL, 0xaac5a2d99c69cfa1L);
    builder.put(0x4d5ca23b0aeaecefL, AttributeDefinition);
    builder.put(0x4d5ca23b0aeaecdeL, AttributeList);
    builder.put(0xe01c95e890f4233L, Check);
    builder.put(0xe01c95e890f4231L, Enrich);
    builder.put(0xe01c95e890f4209L, Query);
    builder.put(0xe01c95e890f4230L, Select);
    builder.put(0xe01c95e890f4232L, StreamDefinition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
