package LEAD.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AttributeDefinition = 0;
  public static final int AttributeList = 1;
  public static final int Check = 2;
  public static final int Enrich = 3;
  public static final int From = 4;
  public static final int Match = 5;
  public static final int NamedStreamReference = 6;
  public static final int Query = 7;
  public static final int StreamDefinition = 8;
  public static final int StreamList = 9;
  public static final int StreamReference = 10;
  public static final int name = 11;
  public static final int test1 = 12;
  public static final int test2 = 13;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xebf7f592fe9245eeL, 0xaac5a2d99c69cfa1L);
    builder.put(0x4d5ca23b0aeaecefL, AttributeDefinition);
    builder.put(0x4d5ca23b0aeaecdeL, AttributeList);
    builder.put(0xe01c95e890f4233L, Check);
    builder.put(0xe01c95e890f4231L, Enrich);
    builder.put(0x45a737ba1a53cddeL, From);
    builder.put(0xe01c95e890f4230L, Match);
    builder.put(0x104ecb43706eb008L, NamedStreamReference);
    builder.put(0xe01c95e890f4209L, Query);
    builder.put(0xe01c95e890f4232L, StreamDefinition);
    builder.put(0x45a737ba1a53ede4L, StreamList);
    builder.put(0x45a737ba1a53cafdL, StreamReference);
    builder.put(0x2febcd1a6a4257c7L, name);
    builder.put(0x2febcd1a6a425774L, test1);
    builder.put(0x2febcd1a6a425777L, test2);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
